// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFaA-lAGX-Lnrzi1TS1xtksSwf3_oLShE',
    appId: '1:143853235640:web:bbc45899dd16687641334d',
    messagingSenderId: '143853235640',
    projectId: 'systm-limpieza',
    authDomain: 'systm-limpieza.firebaseapp.com',
    databaseURL: 'https://systm-limpieza-default-rtdb.firebaseio.com',
    storageBucket: 'systm-limpieza.firebasestorage.app',
    measurementId: 'G-GNGLGZXY4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHyViFH2tklDhuwzH_gg9iGnvPL5vy60',
    appId: '1:143853235640:android:3999b3b602358bc441334d',
    messagingSenderId: '143853235640',
    projectId: 'systm-limpieza',
    databaseURL: 'https://systm-limpieza-default-rtdb.firebaseio.com',
    storageBucket: 'systm-limpieza.firebasestorage.app',
  );
}
